### ISSUE TITLE
Change SMB share 

### ISSUE THREAD

**Issue by tgilis** [purpleteam/snarf#9]
It is possible to specify which share specifically we redirect the request ? 
The problem is that the victim cannot access the root (\\target\) but can access particular share \\target\share$. 

Can you let me know where I can tweak this in the .JS scripts ?

**Comment by jephthai** [comment]
I'm not sure if that makes sense.  When the victim makes a connection, there is an initial authentication, and then a TREE_CONNECT.  The TREE_CONNECT is where the share is specified -- other than successfully authenticating, I'm not sure what you mean by accessing the root.

Anyway, to manipulate the victim's conversation, the relevant code would be in in smbbroker.js, specifically the "reviewServerPacket()" and "reviewClientPacket()" functions.  These collect information about the session and detect when the client logs off.  If you want to change packets, you can add clauses in there and edit the packets.

Note, however, that manipulating the packets is non-trivial sometimes.  If you want to change a field to a longer value, for example, that will throw off the field-length prefixes, and you'll kind of have to recalculate the whole packet.  FYI.
